---
root: true
extends:
- 'airbnb-base'
env: 
  es6: true
  browser: true
  node: true
  jasmine: true
  jest: true
rules: 
    no-console: 0
    import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
      - error
      - ignorePackages
      - js: always
    no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
    import/prefer-default-export: 0

  